### ISSUE TITLE
DPAD toggle options possible?

### ISSUE THREAD

**Issue by RensTillmann** [BOLL7708/OpenVR2Key#10]
Hi, I am not sure if this is not possible at all due to "Hardware" limitation, or the software limitations within the SteamVR Controller Bindings itself, or better said "OpenVR".

Basically what I would like to see is an option for the Joystick, to not only have a simple "DPAD > click" or "DPAD > touch", but also an extra option to do a toggle event/function e.g "DPAD > toggle click", or perhaps you can call it "DPAD TOGGLE BUTTON > click"

See below image what I mean:

![image](https://user-images.githubusercontent.com/16322803/110511231-4e649900-8104-11eb-99e1-da8bbb1851b6.png)

Why I would want this, basically I am now playing some DCS in VR, the issue right now is that normally you'd have a HOTAS, which comes with many buttons. Now what I first had in mind was to just use the left controller buttons X/Y to map it as a toggle, so they become a "Modifier" key. That way I will have 3 levels of mapping options so to speak. However if I would be able to do exactly this but with the Joystick itself, you'd have even more levels. For instance if you'd press DPAD North, it would toggle "Key right 1", which could be mapped to LeftShift (just as an example). This way with just the DPAD you would have 5 layers already, so a total of 6 layers would be possible. Now if you also included the X/Y buttons, you'd have 8 layers in total. That is a lot, because then you'd have 8*10=80 possible buttons, you'd only have buttons for the right controller, with the exception for the Grip and Trigger on your left. (this is for my controllers specifically, obviously it will differ for other controllers I guess).

Anyway, that was basically my idea, what do you think? Will something like this be possible? If not, would there be some alternative to achieve this, perhaps even in combination with some other extra piece of software.

I probably don't even need the above, but it's just an idea, and might be quite nice. I am probably OK with the X/Y toggle buttons for the time being, but DCS is so complicated, and it's nice to play the game without a HOTAS, because yeah, more immersive, since you click buttons in the cockpit with your hands. It's not great to have to put down the controllers and then switch to the HOTAS.

**Comment by BOLL7708** [comment]
I've poked around and yeah, for the DPAD input type there is only touch and click, and that's part of the API so pretty sure I'd have to make something externally to keep track of that. It means it would have to be implemented in the application interface, as a checkbox or similar... possible, but pretty sure it's not going to happen, sorry 😅 Anything is possible, it just takes time and effort and consideration.

What I would say though, is take a look at chords. It might be a hassle to set everything you want up, but you can register button combinations to trigger other inputs. Might not enable exactly what you want, but perhaps it can be partially useful at least.

**Comment by RensTillmann** [comment]
Yes, I was already afraid that the OpenVR had the limitations. Anyway your tool is a great addition to have for sure, and already helped me a lot. I think with some fiddling around I might be able to get it to work, there are just some limitations within DCS bindings. I hope they will implement something like VTOL VR has, that's just great! But that's another topic :) I will close this "issue" now, have a good day! 👍
