### ISSUE TITLE
active input blocked

### ISSUE THREAD

**Issue by jakepaul1234sk** [BOLL7708/OpenVR2Key#117]
### Current behavior

keeps saying blocked every time I open it up

### Steps to reproduce the behavior

1 load up meta app 2 open steam vr 3 load openvr2key 4 gets blocked 5 give up

### Expected behavior

I open up steam Vr and openvr2key and i go into my headset and I look at openvr2key and it says "active input: blocked"

### Operating system version

Windows 10

### SteamVR version

2.7.4

### Application version

2.1.1

### Application location

C:\Desktop\Openvr2key\

### VR HMD

Quest 3

### VR hardware

Quest 3 controllers

### Software to control

Soundpad

### Game

gorilla tag

### Additional information

No photo

**Comment by BOLL7708** [comment]
Dismiss the SteamVR dashboard.

**Comment by jakepaul1234sk** [comment]
> Dismiss the SteamVR dashboard.

how do i do that

**Comment by BOLL7708** [comment]
Click the appropriate system button that launch it or the trigger while aiming outside of it. If you have ever used SteamVR this should be something you have done plenty of times.
