### ISSUE TITLE
Questions: autostart, multikey bind

### ISSUE THREAD

**Issue by lynrayy** [BOLL7708/OpenVR2Key#120]
### Question

1. How to make it autostart with SteamVR?
2. How to make custom bind with multiple controller keys condition? I want to do this:
When i touch steamVR button on the left controller and SteamVR button on right at the same time, OpenVT2Key emulate PrtSc button

### Operating system version

windows 11

### SteamVR version

latest

### Application version

v2.1.1

### VR HMD

Valve Index

**Comment by BOLL7708** [comment]
1. It automatically registers for auto-launching just by running the executable. You can disable that by going into startup settings in SteamVR where it should be listed as an overlay application.
2. In the bindings editor, create a chord (button in the middle of the editor)), choose a Chord Key for that, which is C1, C2 etc in the application. Those are especially made to handle chords.

**Comment by lynrayy** [comment]
> It automatically registers for auto-launching just by running the executable. 

Startup not working.

> In the bindings editor, create a chord (button in the middle of the editor)), choose a Chord Key for that, which is C1, C2 etc in the application. Those are especially made to handle chords.

Made chord that activate L1 when left menu and right menu touched. Program registered L1, but:
1. None of keys emulated (PrtSc, combination, win button) when L1 activates
2. L1 sometimes stuck enabled

**Comment by lynrayy** [comment]
P.s. I previously untied L1 and R1 from the controllers in the controller settings, so this cannot be a problem with L1 sticking

**Comment by BOLL7708** [comment]
If the start up doesn't work, I'd delete the executable and cycle SteamVR so it will unlist the previous registration. Then run a fresh installation and see if that makes any difference. That, or you can enter the SteamVR startup settings and see if it's listed and switched on there.

As I mentioned, you should use the C keys for chords, they are made specifically for chords that are handled differently from other actions. Try that and see if it makes any difference.
