### ISSUE TITLE
App not registering PrtSc key

### ISSUE THREAD

**Issue by lynrayy** [BOLL7708/OpenVR2Key#121]
### Current behavior

App not registering PrtSc key

Issue:
https://youtu.be/uWF-YRgM3Vg

### Steps to reproduce the behavior

Select bind
Press PrintScreen key on keyboard
Press RMB
In config it will be empty

### Operating system version

windows 11

### SteamVR version

Latest

### Application version

Latest

### Application location

`D:\Program Files\.Portable\OpenVR2Key_v2.1.1`

### VR HMD

Valve Index

### Software to control

ShareX

**Comment by lynrayy** [comment]
Whyt it is "A" have 44 number if https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes says that 44 is for PrtSc number?

**Comment by lynrayy** [comment]
How can i manually set Alt+PrtSc in config? ([120,???])

**Comment by BOLL7708** [comment]
The key numbers are what the system provide, they are mapped against virtual key codes to simulate the matching input, and now when I checked I cannot find PrtScr in the set of codes that are provided, so it is not mapped. It is entirely possible that PrtScr specifically cannot be simulated, I'm using this library for the simulation: https://github.com/GregsStack/InputSimulatorStandard

**Comment by lynrayy** [comment]
Anyway a am using ALT+F12 for now. It is easier to change bind in ShareX than fix software
