### ISSUE TITLE
Will it be possible to do the opposite

### ISSUE THREAD

**Issue by matthgyver** [BOLL7708/OpenVR2Key#123]
Hi,

In the future, will it be possible to do the opposite, i.e. make pressing a key on the keyboard play a key on the controller?
Perhaps there's already an application for this, but I haven't found anything :-/

Thank you

**Comment by BOLL7708** [comment]
It's not super straight forward. It takes doing driver injection or a virtual driver, or both, I'm not entirely sure how it's done. But, there was a [project}(https://github.com/matzman666/OpenVR-InputEmulator) for it but it hasn't been updated in six years. It is well outside the scope of this project though, and beyond my skills as well, even if I want the feature myself for things like trigger auto-fire.
