### ISSUE TITLE
Doesn't work with Virtual Desktop

### ISSUE THREAD

**Issue by Hesbon88** [BOLL7708/OpenVR2Key#14]
Doesn't work with Virtual Desktop, when the application is opened in Steam, the configuration is simply deactivated or does not work.
(Oculus rift S)

**Comment by BOLL7708** [comment]
I'm currently melting in the heat, so I'll leave you with a few questions for now, before I take a look at this:

1. When you say configuration, is that in this application, the key mappings, or are you talking about the input bindings in SteamVR?
2. When you say it's deactivated, does that mean it's disabled, showing for the wrong application, you cannot find it, or what exactly does this mean?

A screenshot of the problem could also help a lot 😁

**Comment by BOLL7708** [comment]
As it has been so long and there has been no further information provided I'm closing this. Reopen it with more details if this is still an issue.
