### ISSUE TITLE
Need binding for LB and RB on Valve Index knuckle controllers

### ISSUE THREAD

**Issue by mswann63** [BOLL7708/OpenVR2Key#17]
The center-press function of the left and right joysticks on the Valve Index knuckle controllers should be mappable.

**Comment by BOLL7708** [comment]
The left stick click is bound to `Key L8` by default, and the right stick click to `Key R8` by default. Did you edit the bindings? In that case you need to add a `Use as button` binding to the `Thumb stick` and add something to the `Click` event. Report back here or close the ticket if it works for you or not.

**Comment by mswann63** [comment]
Hi. Thanks for responding. I’m not talking about L8 and R8. I’m talking about LB and RB. Sent from Mail for Windows From: Andreas AronssonSent: Sunday, February 20, 2022 8:56 AMTo: BOLL7708/OpenVR2KeyCc: Mark Swann; AuthorSubject: Re: [BOLL7708/OpenVR2Key] Need binding for LB and RB on Valve Index knuckle controllers (Issue #17) The left stick click is bound to Key L8 by default, and the right stick click to Key R8 by default. Did you edit the bindings? In that case you need to add a Use as button binding to the Thumb stick and add something to the Click event. Report back here or close the ticket if it works for you or not.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by mswann63** [comment]
You can close this.
