### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by bibs38dm** [BOLL7708/OpenVR2Key#19]
in the active keys it says unblocked and i cant see what button is active when pressing. any solution?

**Comment by BOLL7708** [comment]
Unblocked is the status that is set when the SteamVR dashboard has been dismissed: As soon as input is provided after that it will replace that string with whatever was pressed.

What headset/controllers are you using?

**Comment by BOLL7708** [comment]
As I haven't heard anything in a week I'll close this and you'll have to reopen it if you still have an issue.
