### ISSUE TITLE
This application is already running.

### ISSUE THREAD

**Issue by bbo1129** [BOLL7708/OpenVR2Key#21]
When I try to open OpenVR it gives me a pop up message that says This application is already running. This makes me unable to map out the bindings. Is there a way to open it so i can map out my keys?

**Comment by BOLL7708** [comment]
It should only say that if it finds a running copy of itself. The application registers with SteamVR to auto-launch the next time SteamVR is launched, and it can auto-minimize to tray, so just maybe it is actually running already. Can you check your running processes to make sure another instance is not already running?

**Comment by bbo1129** [comment]
I do recall me checking the auto-minimize tab so I think that's the problem. Is there a way I can get that un-minimize?

**Comment by bbo1129** [comment]
There is an instance of OpenVR2Key open but when I try to open it or click it, it does nothing.

**Comment by BOLL7708** [comment]
To get to it when minimized and not in the task bar, click the application icon in the system tray, the icons near the clock on the taskbar.

**Comment by BOLL7708** [comment]
As there has been no more comments here I'm going close this with the assumption that the issue was resolved with the above information.
