### ISSUE TITLE
Will not show up in "Manage Controller Bindings"

### ISSUE THREAD

**Issue by Turnrp** [BOLL7708/OpenVR2Key#22]
![image_2022-05-29_152549204](https://user-images.githubusercontent.com/70816015/170888154-4f87846d-da0a-4a1c-a05f-bbaec5a8e1da.png)

**Comment by BOLL7708** [comment]
Yeah this is something with the new SteamVR interface. You need to use the old one now to see it listed, or add it to your VR library, as talked about [here](https://github.com/BOLL7708/OpenVR2Key/issues/6).
