### ISSUE TITLE
It just automatically closes?

### ISSUE THREAD

**Issue by Wrevel-the-gorilla** [BOLL7708/OpenVR2Key#25]
when i try to open it while steamVR is open, it just closes automatically.

**Comment by BOLL7708** [comment]
Is there no dialog? It only allows one instance to be running, but should notify you of that, otherwise the only thing it should rely on is .NET 4.7.2 🤔 Anything show up in the Event Viewer?

**Comment by BOLL7708** [comment]
No more details to go on so closing this.
