### ISSUE TITLE
How do I bind the menu buttons? (Index Controllers)

### ISSUE THREAD

**Issue by Viperlotus** [BOLL7708/OpenVR2Key#26]
I'm trying to setup this program, but when I go to the bindings editing menu for SteamVR, it gives me the option to rebind everything except the menu buttons, which are the one thing I actually want to bind into a push to toggle mute for Discord.  I looked at the clips on the setup instructions and it shows you can bind the menu button in the first one, but that just isn't happening for me for some reason.

**Comment by BOLL7708** [comment]
You can't rebind the system button click in SteamVR, or at least that has been the case in the past, it should be impossible in any third party game or app on Steam. What we can bind is the touch event on the system buttons, which is why it's in there at all.
