### ISSUE TITLE
Will not switch configurations for different apps.

### ISSUE THREAD

**Issue by DigitizedLife** [BOLL7708/OpenVR2Key#27]
I am receiving the following error in the log window. Not sure if the error is the reason for not loading individual app configurations.

The default configuration works great. But it does not switch when I switch apps.

![Screenshot 2022-09-13 010048](https://user-images.githubusercontent.com/113411626/189813557-1ed146c2-ce31-46bc-8476-3c0a8d593374.png)

**Comment by DigitizedLife** [comment]
I am using VPX VR-Launcher 4.exe (Visual Pinball VR Launcher) and VPinballX_VR.exe (Visual Pinball X VR). I can create the configs for them when they are running and they are saved in the config folder with the proper app id, but when I run either of the apps they only use the default config even though the proper app id is shown.

**Comment by BOLL7708** [comment]
What app IDs do they show up as having? As they seem to be executables from outside of Steam, perhaps their generated names have bumped into an incompatibility... 🤔

And the error should indeed show up every time as it goes to an invalid value before getting an actual value with the next title. This is why I'm thinking it might be best to suppress these messages.

**Comment by DigitizedLife** [comment]
![screens](https://user-images.githubusercontent.com/113411626/189990342-963b1052-fa07-441c-a916-9e59f2302c09.jpg)

**Comment by DigitizedLife** [comment]
I just figured it out after looking at the screen shots. The file names of the configs are wrong (missing non text characters). I correct the file names to accurately reflect the app names and it all works!

**Comment by BOLL7708** [comment]
Oh look at that, there are spaces in the generated IDs, I honestly had no idea that was possible 😅 I uh... might have to look at this. Thanks for figuring it out 🤣 I'll have to sync the lookup of files to also remove the spaces, pretty sure I use some standard component to write the files, as such I was surprised this happened 🙃 (or it's my code, it's been a while)

**Comment by BOLL7708** [comment]
I pushed a pre-release version [here](https://github.com/BOLL7708/OpenVR2Key/releases/tag/v0.59) with a potential fix, if you have the time for it, please try this version and see if it fixed this issue!
