### ISSUE TITLE
Using 58 trying to use launcher

### ISSUE THREAD

**Issue by brodzowski** [BOLL7708/OpenVR2Key#28]
I have a launcher I'm using and when it first loads up - if I'm very fast I can get a couple key presses out of it but then it loads with an error -- GetRunningApplicationid error: InvalidParameter       Anything I can do?

**Comment by BOLL7708** [comment]
What launcher are you using? Getting the app ID will fail, gracefully, if you don't have a scene application (like a game) running in SteamVR. What are you trying to add keys for?

**Comment by brodzowski** [comment]
I am also on the vpx train and found that it actually had native support I could turn on but it's called VPX VR-Launcher 4 -- It's not a game but rather the launcher that loads the tables. An "interface" so to speak. Runs in Unity. Would trying to add it to my steam library give it an ID? Like I said - at this point it doesn't matter because it has native controls, but for the future--- and the space in the filename for VPinballX_GL.exe is still there. Luckily I found that previous problem to read and save me. It still exists, however.

**Comment by BOLL7708** [comment]
Oh, it's the problem with unexpected spaces in the generated app ID? I presume this is the same as #27 then, I'll close this as this tag creates a cross-reference to this thread, marked as duplicate. And no I haven't worked on this project recently to fix this, working on a major update for a different project, but when that is done I need to take a look at this 😅

**Comment by BOLL7708** [comment]
I pushed a pre-release version [here](https://github.com/BOLL7708/OpenVR2Key/releases/tag/v0.59) with a potential fix, if you have the time for it, please try this version and see if it fixed this issue!
