### ISSUE TITLE
Is there a way to use meta quest 2 controllers?

### ISSUE THREAD

**Issue by poofpoof505** [BOLL7708/OpenVR2Key#31]
I have a meta/oculus quest 2 and I was trying to use this for key binding to my soundboard but I cant bind my controller keys to it. Is it just not compatible with my controller or am I doing something wrong?

**Comment by BOLL7708** [comment]
I'm not actually sure 😅 I don't collect any kind of data so I don't know what headsets people are using this application with. You could check if there are custom bindings for the Quest 2 when checking for custom bindings.

**Comment by poofpoof505** [comment]
Ok thank you, if you do make a specific one for the meta quest 2 let me know otherwise it's not working for me.

**Comment by RitzyCash** [comment]
i have tried with the quest 2 controllers everything seems to be fine

**Comment by BOLL7708** [comment]
Thanks for reporting your success! @RitzyCash Did it work with the included Oculus bindings, or did you have to create your own custom bindings?

**Comment by RitzyCash** [comment]
it worked with the included ones

**Comment by BOLL7708** [comment]
Thanks! I'll mark this as closed 😁

**Comment by poofpoof505** [comment]
@RitzyCash What settings did you use to get the results?
