### ISSUE TITLE
Can bind chest trackers, but not camera trackers

### ISSUE THREAD

**Issue by codingcatgirl** [BOLL7708/OpenVR2Key#32]
This is an awesome tool, i tried it out yesterday and looks like i can control OBS now using buttons on the tracked camera – neat! There's only one downside: I have to set the tracker to be a Chest tracker, Waist tracker, or some other destination that OpenVR2Key supports. If i set it to be a camera tracker (under "manage trackers")… i can set bindings, but they won't work. So it looks like not all tracker "types" are supported. Can these be added please? 

This sounds easily doable to me but skimming the code i didn't find it immediately. Might take another look in a bit and submit a pull request if i can find it, but i bet it can be done quicker by someone who is familiar with the codebase and already has the dev setup setup ^^

**Comment by BOLL7708** [comment]
I made an experimental build with a bunch of additional tracker roles added, camera included: https://github.com/BOLL7708/OpenVR2Key/releases/tag/v0.60

Experimental as my VR hardware is malfunctioning at the moment, so you'll have to get back to me if this is working or not 😅

**Comment by BOLL7708** [comment]
And I forgot to actually update the code, that release only includes the new bindings, stand by...

**Comment by BOLL7708** [comment]
Here, try this instead: https://github.com/BOLL7708/OpenVR2Key/releases/tag/v0.61

**Comment by codingcatgirl** [comment]
Damn, that was quick – Thank you so much! Unfortunately i'll only be able to try it when i'm back home later this month :D But thank you so much <3

**Comment by evilscientress** [comment]
I should be able to test it later today.

**Comment by evilscientress** [comment]
Just tested it and I can confirm it works :)
Thanks very much for the quick fix!

**Comment by BOLL7708** [comment]
Good to hear, will close this for now 😁👍
