### ISSUE TITLE
Support with oculus pc app

### ISSUE THREAD

**Issue by xalaxium** [BOLL7708/OpenVR2Key#34]
I've tried out this software and it works perfectly as intended, but I would enjoy if you added support with the oculus app instead of it just being exclusive to steamvr.

**Comment by BOLL7708** [comment]
This is specifically built using the OpenVR APIs for listening to input and other features, there are currently no plans to implement the Meta VR APIs, there's just not any development bandwidth available for that, and at this point I don't even know if they support things like background applications that listen to controller input. 

This might change if I actually end up getting a Meta headset at any point in the future.
