### ISSUE TITLE
Keeps saying Loading Current Binding in the manage controller binding section

### ISSUE THREAD

**Issue by 2tmb2** [BOLL7708/OpenVR2Key#4]
In the steamVR manage controller bindings section, it constantly says "Loading current binding" instead of giving me the option to change it to custom. Every other app works fine. I have added a screenshot as an example.
<img width="598" alt="loadingcurrentbinding" src="https://user-images.githubusercontent.com/59399953/85042421-08b00c80-b140-11ea-979a-45e01b7e80b4.PNG">

**Comment by BOLL7708** [comment]
Yup, I [reported](https://steamcommunity.com/app/250820/discussions/3/2251181585643234780/) something similar in the SteamVR forums back in early May, when it was still only in the beta, but it was pushed to live later on anyway 🤷‍♂️ Have gotten confirmation that it's probably being looked into, but that's about it. 🙄 I've experienced the thing in your screen capture on multiple occasions. 🙁

**Comment by 2tmb2** [comment]
Do you know how to fix it? This was exactly what I was looking for and would love for it to work. Every other app I tested worked, so I thought it was something specifically for this app, and I was wondering if I did anything wrong. If it is possible to fix it, could you tell me? Thanks.

**Comment by BOLL7708** [comment]
Slap my face, I thought this was posted to the OpenVR repo, thus my above comment, I hardy ever get any activity on my own projects so didn't realize it was here.

I haven't been able to figure out what causes it, and I've only ever had it happen when other titles are running at the same time, so I imagine it might be some kind of collision? I've experienced it myself though, of course, but I will try activating some additional logging and see if something pops up.

I'm currently finishing off a different project so I'm slightly distracted right this moment 😅

**Comment by BOLL7708** [comment]
@2tmb2 I've been trying to trigger this now by running various games at the same time as this application, and my other applications, which usually had it break fairly quickly. I do notice that the issue I had submitted to the SteamVR forums seems to now be fixed, so maybe this is also fixed?

In any case, could you test this again with the latest SteamVR beta, 1.13.5, and tell me if you still experience the issue?

**Comment by 2tmb2** [comment]
@BOLL7708 I am unable to update to the beta update; when I click update it doesn't do anything.

**Comment by BOLL7708** [comment]
@2tmb2 Have you selected the beta? In Steam, search for SteamVR, right-click the tool and choose `Properties...`, select the tab `Betas` and in the drop-down choose `beta - SteamVR Beta Update`, then click `CLOSE`.

This should, as soon as you shut SteamVR down, download the latest beta version of SteamVR. It's a priority download so will trigger immediately as soon as it can. When download finishes you can launch it again, it should say `SteamVR [beta]` in the library.
