### ISSUE TITLE
Error invalid parameter

### ISSUE THREAD

**Issue by LazerReload** [BOLL7708/OpenVR2Key#46]
Every time I open it up it says in the active keys section that it’s Blocked and it says in the log GetRunningAplicationld error: InvalidParameter how do I fix this

**Comment by BOLL7708** [comment]
Input is blocked if the SteamVR dashboard is up. Getting the app ID will fail if there is no game running. I have plans to change this working or hide the log by default because it's not actually helping people.

**Comment by BOLL7708** [comment]
Closed due to no reply.
