### ISSUE TITLE
Key signal auto repeat

### ISSUE THREAD

**Issue by guillaumarie** [BOLL7708/OpenVR2Key#48]
Hi!
Is there a way to set the signal on auto repeat when holding a key (like on a normal keyboard)?
The issue doesn't seem to come from my controllers as it works in video games

**Comment by BOLL7708** [comment]
I have not added a repeat function no, it never even crossed my mind as I almost never use that feature on purpose myself. Is this a huge issue? In which situations would this feature be beneficial that is a common use case?

**Comment by guillaumarie** [comment]
It might be a bit specific indeed, I’m

**Comment by guillaumarie** [comment]
It might be a bit specific indeed, I’m trying to use a Valve Index controller joystick as direction arrows to move an object in a software which wasn’t developed for VR (my final use is in VR but this software is only an intermediary). It works well (thanks a lot btw!) but I need to press the joystick repeatedly instead of just pressing once as long as I need.

**Comment by BOLL7708** [comment]
I honestly think this should be something Valve adds to their DPAD input mode, it would make sense there 😅 that could enable an auto-fire mode though and so far they haven't done that for anything yet >_> I sure could use that in some pew pew games in VR.

The main problem with adding this would be the additional interface components, which is the annoying part really. Adding the system functionality is pretty straight forward but then it has to make sense in the larger context 🤔 I'm currently engaged in a different project so might not think deeper about this for a while 😬

**Comment by guillaumarie** [comment]
Thanks for your answer, I understand!
I finally managed to do what I wanted using the "Center" state of the DPAD and waiting for this signal to stop the move (I couldn't use the 'release' state of other buttons because of other constraints).
