### ISSUE TITLE
Open2VRKey

### ISSUE THREAD

**Issue by exoticvr0** [BOLL7708/OpenVR2Key#50]
Can someone please help me out .... when I open open2vrkey.exe - it shows all white and I can't see any numbers or letters. 
![Screenshot 2023-05-29 220611](https://github.com/BOLL7708/OpenVR2Key/assets/134995200/a08236bd-5d7c-454f-9061-70fc1d10e98c)

**Comment by exoticvr0** [comment]
help

**Comment by BOLL7708** [comment]
What Windows version are you running?

**Comment by exoticvr0** [comment]
10

**Comment by BOLL7708** [comment]
Are you running some custom theme? I guess I could fix this by specifically setting the background color on the views that now apparently were transparent, I haven't seen this issue before.

**Comment by exoticvr0** [comment]
i dont know how i check

**Comment by exoticvr0** [comment]
it came like that

**Comment by exoticvr0** [comment]
Thank you! I turned off high contrast

**Comment by BOLL7708** [comment]
I guess that fixed it, thanks for confirming! I'm closing this for now and will make a note about the background colors 😅
