### ISSUE TITLE
I DONT UNDERSTAND I NEED HELP PLS!!!

### ISSUE THREAD

**Issue by JingleBingle000** [BOLL7708/OpenVR2Key#53]
i swear im the only person with this issue ive seen nothing on it and nobody else with it am i just dumb or am i doing something wrong???
![Screenshot 2023-06-05 213345](https://github.com/BOLL7708/OpenVR2Key/assets/135678565/aa69ba2e-f63b-4567-8df3-c025606ddfe1)

**Comment by BOLL7708** [comment]
Uhm, what is the actual issue here?

**Comment by JingleBingle000** [comment]
> Uhm, what is the actual issue here?

the issue is that it wont tell me what buttons i have press causing it not to work all it says is unblocked it wont do anything else

**Comment by BOLL7708** [comment]
Ah sorry, missed that you had replied. Did you actually solve it? Otherwise I would ask things like...
* What hardware are you using.
* What OS are you on.
* Are you running a game at the same time.
* Is the dashboard visible.
Things like that.
