### ISSUE TITLE
how do you delete this

### ISSUE THREAD

**Issue by lollolololololl** [BOLL7708/OpenVR2Key#54]
its crashing  please help me

**Comment by BOLL7708** [comment]
When you are asking for help it makes sense to provide a bit more details or else it will be near impossible to actually assist.
1. Do you find anything in the Event Viewer? 
2. Was there any error dialog?
3. Are you running SteamVR when this happens?
4. What headset and runtime are you using?
5. What OS version and GPU driver are you running?

**Comment by lollolololololl** [comment]
my game crashes when I open steam vr

**Comment by BOLL7708** [comment]
... the game is crashing, not this application? What game are you running?
