### ISSUE TITLE
when i log into my game the sounds go away

### ISSUE THREAD

**Issue by prestono55** [BOLL7708/OpenVR2Key#59]
what do i do

**Comment by BOLL7708** [comment]
1. What game is it?
2. Are you actually running OpenVR2Key?
3. What headset are you using?
4. Is SteamVR running?
5. What OS version are you on?
6. Are you using a software mixer like Voicemeeter?

**Comment by prestono55** [comment]
gorilla tag
yes, i think
meta quest `two
yes
idk
im using soundpad

**Comment by BOLL7708** [comment]
I've seen other people post about this combination of things. OpenVR2Key does not interact with audio systems on the host machine at all, to my memory, so I'd say this has more to do with some other component, like Soundpad.
