### ISSUE TITLE
OpenVR2Key not in Binding Dropdown

### ISSUE THREAD

**Issue by nicokimmel** [BOLL7708/OpenVR2Key#6]
Hey,
OpenVR2Key not in the binding dropdown for some reason. The only way I can edit it is in VR if I press "Show more Application". But then it does not work ingame, only in SteamVR Home.

**Comment by BOLL7708** [comment]
Yeah, sadly I don't know how to fix this, it happens for other applications as well (not made by me) 🤷‍♂️ I've reported [an issue](https://github.com/ValveSoftware/openvr/issues/1435) regarding it over at Valve's repository for OpenVR.

**Comment by Flix1001** [comment]
Hello there, is this about [this](https://github.com/BOLL7708/OpenVR2Key#steamvr-input) step? If so I have the same problem..

**Comment by kotabird** [comment]
I've so far reinstalled OpenVR2, SteamVR, and Steam itself multiple times. So far no luck in seeing OpenVR2 in the dropdown... very frustrating. I know for a fact it's possible because I just did it yesterday prior to reformatting my HDD.

**Comment by kotabird** [comment]
> I've so far reinstalled OpenVR2, SteamVR, and Steam itself multiple times. So far no luck in seeing OpenVR2 in the dropdown... very frustrating. I know for a fact it's possible because I just did it yesterday prior to reformatting my HDD.

I'VE FIGURED IT OUT! Make sure after you have added OpenVR2 to your steam library make sure to right click > properties > INCLUDE IN VR LIBRARY. I did that an HOORAY it showed up!

**Comment by Flix1001** [comment]
> > I've so far reinstalled OpenVR2, SteamVR, and Steam itself multiple times. So far no luck in seeing OpenVR2 in the dropdown... very frustrating. I know for a fact it's possible because I just did it yesterday prior to reformatting my HDD.
> 
> I'VE FIGURED IT OUT! Make sure after you have added OpenVR2 to your steam library make sure to right click > properties > INCLUDE IN VR LIBRARY. I did that an HOORAY it showed up!

OpenVR2Key doesn't show up in my steam library...do I add it manually? That's shouldn't be necessary right?

**Comment by kotabird** [comment]
> > > I've so far reinstalled OpenVR2, SteamVR, and Steam itself multiple times. So far no luck in seeing OpenVR2 in the dropdown... very frustrating. I know for a fact it's possible because I just did it yesterday prior to reformatting my HDD.
> > 
> > 
> > I'VE FIGURED IT OUT! Make sure after you have added OpenVR2 to your steam library make sure to right click > properties > INCLUDE IN VR LIBRARY. I did that an HOORAY it showed up!
> 
> OpenVR2Key doesn't show up in my steam library...do I add it manually? That's shouldn't be necessary right?

Yes, so what you need to do with steam is go to the top in Games>add non-steam game to my library>find OpenVR2 and add.
It should show up after that, then you want to make sure to add it specifically into the VR library :)!

**Comment by rsiefkas** [comment]
> > I've so far reinstalled OpenVR2, SteamVR, and Steam itself multiple times. So far no luck in seeing OpenVR2 in the dropdown... very frustrating. I know for a fact it's possible because I just did it yesterday prior to reformatting my HDD.
> 
> I'VE FIGURED IT OUT! Make sure after you have added OpenVR2 to your steam library make sure to right click > properties > INCLUDE IN VR LIBRARY. I did that an HOORAY it showed up!

I've been banging my head against SteamVR for half an hour trying to make this work.  After a half dozen google searches, I found this comment.  Thank you so much for sharing a solution.

**Comment by Dalethium** [comment]
> > I've so far reinstalled OpenVR2, SteamVR, and Steam itself multiple times. So far no luck in seeing OpenVR2 in the dropdown... very frustrating. I know for a fact it's possible because I just did it yesterday prior to reformatting my HDD.
> 
> I'VE FIGURED IT OUT! Make sure after you have added OpenVR2 to your steam library make sure to right click > properties > INCLUDE IN VR LIBRARY. I did that an HOORAY it showed up!

I am entirely convinced that you are a profit. Thank you so much.

**Comment by BOLL7708** [comment]
Just took me a few years to get around to this, the readme now has a [section](https://github.com/BOLL7708/OpenVR2Key/edit/master/README.md#steam-library) about this.
