### ISSUE TITLE
active keys dont work

### ISSUE THREAD

**Issue by goofyguy72** [BOLL7708/OpenVR2Key#60]
active keys just say unblocked and nothing else

**Comment by BOLL7708** [comment]
It will not show anything else if SteamVR is not running and the SteamVR dashboard cannot be visible in the headset.

**Comment by goofyguy72** [comment]
Steamvr is open with gorilla tag open and the dashboard is completely closed

**Comment by goofyguy72** [comment]
> It will not show anything else if SteamVR is not running and the SteamVR dashboard cannot be visible in the headset.

Steamvr is open with gorilla tag open and the dashboard is completely close

**Comment by BOLL7708** [comment]
It should work if you have controllers that there are bindings for, what do you see if you go into the bindings interface? If there are no bindings you need to do custom ones.

**Comment by goofyguy72** [comment]
> It should work if you have controllers that there are bindings for, what do you see if you go into the bindings interface? If there are no bindings you need to do custom ones.

i am using oculus quest 2

**Comment by H4mser** [comment]
I'm having the same problem. When I press the A button, nothing pops up it just says "Unblocked"

**Comment by goofyguy72** [comment]
> I'm having the same problem. When I press the A button, nothing pops up it just says "Unblocked"

SAME

**Comment by BOLL7708** [comment]
Did you figure it out @goofyguy72 ? I've been moving apartments so have not had much energy to engage on issues here, or have simply forgotten 😅

**Comment by H4mser** [comment]
Yes I found out how to fix it.
