### ISSUE TITLE
Keys Not working for soundpad

### ISSUE THREAD

**Issue by da123487** [BOLL7708/OpenVR2Key#62]
I did everything right it's just it won't work I did some other research on this page to see if I could fix it, and some things related to mine were about mapping the keys??? but I just need to get it to where if I make multiple keys like if my A button on my controller is R14 and my X button L14 I said L14 for left 14 key you get it, and I set the same hotkey for the same one my soundboard has and VR2KEY has and I press a button on my controller which is supposed to play a sound nothing happens.                                                                                                 

Can You Help Me With This???

**Comment by BOLL7708** [comment]
Does the soundboard work if you use the same hotkeys on your keyboard?

**Comment by BOLL7708** [comment]
Closed due to no reply.
