### ISSUE TITLE
the active keys are not working 

### ISSUE THREAD

**Issue by boi-999** [BOLL7708/OpenVR2Key#63]
hello my active keys are saying that its unblocked? i do not know what it is pls help

**Comment by BOLL7708** [comment]
It means the SteamVR dashboard is not shown, so input will be detected, if the dashboard is up input is blocked.
I should make the status less... confusing, a lot of people ask about this, this project is high on the list to get updates when I'm satisfied with my current project.

**Comment by BOLL7708** [comment]
Closed due to no reply.
