### ISSUE TITLE
active keys not working

### ISSUE THREAD

**Issue by gefefnniajjfajfiosni** [BOLL7708/OpenVR2Key#64]
every time i press a key it just says unblocked and nothing else i tried restarting it and still nothing happend does anyone know how to fix

**Comment by BOLL7708** [comment]
Unblocked just means the SteamVR dashboard is confirmed as dismissed, it is not an error. If the dashboard is visible it will block input and then the status is blocked instead.

**Comment by Cycle89** [comment]
I Have the same problem but steamvr dashboard is visible and it still says unblocked when i open steamvr in my oculus headset which it still doesn't exactly work I'm not sure if i do it right it will use my headset and controllers cant confirm if it actually connects or not and it still says unblocked

**Comment by BOLL7708** [comment]
Closed due to no reply.
