### ISSUE TITLE
active keys says unblocked when i press a button nothing works and does not show up when i open steam vr

### ISSUE THREAD

**Issue by cdub1111** [BOLL7708/OpenVR2Key#66]
**Describe the bug**

**To Reproduce**
1. Run game '...'
2. Run software '....'
3. Set input to '....'
4. Set keys to '...'
5. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 Pro]
 - SteamVR Version [e.g. 1.26]
 - Application Version [e.g. 1.46]

**VR Hardware (please complete the following information):**
 - HMD: [e.g. Valve Index]
 - Controllers: [e.g. Valve Index Controllers]

**Games and software (please complete the following information):**
- Game(s) that you are running [e.g. Half-Life: Alyx]
- Software that you are trying to control [e.g. Discord]

**Additional context**

**Comment by cdub1111** [comment]
i  have tried every thing i can think of but still nothing when i open voice mod and steam vr OpenVR2Key will not show up or work if any one can help thinks

**Comment by BOLL7708** [comment]
As I don't know what you have thought of, and I have no experience with voice mod, and don't know what hardware you are using, I can't be of much help. The template you posted unedited was supposed to help with parts of this.

**Comment by BOLL7708** [comment]
Closed due to no reply.
