### ISSUE TITLE
it just says active keys: "unblocked"

### ISSUE THREAD

**Issue by eliasdaviscraig** [BOLL7708/OpenVR2Key#67]
**Describe the bug**

**To Reproduce**
1. Run game '...'
2. Run software '....'
3. Set input to '....'
4. Set keys to '...'
5. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 Pro]
 - SteamVR Version [e.g. 1.26]
 - Application Version [e.g. 1.46]

**VR Hardware (please complete the following information):**
 - HMD: [e.g. Valve Index]
 - Controllers: [e.g. Valve Index Controllers]

**Games and software (please complete the following information):**
- Game(s) that you are running [e.g. Half-Life: Alyx]
- Software that you are trying to control [e.g. Discord]

**Additional context**

**Comment by eliasdaviscraig** [comment]
nvm solved it

**Comment by goofyguy72** [comment]
> nvm solved it

how did you solve it?
