### ISSUE TITLE
i opend steamvr and soundpad pro but the active key says blocked and i dont know what to do :(

### ISSUE THREAD

**Issue by KrissWarrior** [BOLL7708/OpenVR2Key#68]
**Describe the bug**

**To Reproduce**
1. Run game '...'
2. Run software '....'
3. Set input to '....'
4. Set keys to '...'
5. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 Pro]
 - SteamVR Version [e.g. 1.26]
 - Application Version [e.g. 1.46]

**VR Hardware (please complete the following information):**
 - HMD: [e.g. Valve Index]
 - Controllers: [e.g. Valve Index Controllers]

**Games and software (please complete the following information):**
- Game(s) that you are running [e.g. Half-Life: Alyx]
- Software that you are trying to control [e.g. Discord]

**Additional context**

**Comment by BOLL7708** [comment]
Blocked means the SteamVR dashboard is visible, dismiss it.
