### ISSUE TITLE
Minimize On Launch

### ISSUE THREAD

**Issue by thegodlytwo** [BOLL7708/OpenVR2Key#70]
### Current behavior

When I put on Minimize on Launch when ever I open it now it opens but i cant see it anywhere but if i try to open it again it says already opened.

### Steps to reproduce the behavior

1. Click Minimize On Launch
2. Close App
3. Reopen App

### Expected behavior

I thought it was going to just make it minimize and put it on my pinned bar

### Operating system version

Windows 10

### SteamVR version

1.26.6

### Application version

v0.57

### VR HMD

Oculus Quest 2

### VR hardware

Oculus Quest 2

### Software to control

Soundpad

### Game

Gorilla Tag

**Comment by BOLL7708** [comment]
Do you not get an icon in the system tray? It looks like the logo for this repository, if you don't show all tray icons there should be something to click to display them.

**Comment by BOLL7708** [comment]
Closed due to no reply.
