### ISSUE TITLE
Unblocked?

### ISSUE THREAD

**Issue by NokoiGuess** [BOLL7708/OpenVR2Key#71]
### Current behavior

when ever i open the app and try to press a key on my oculus quest 2 controller it says unblocked, and when i press a button nothing shows u
![image_2023-07-26_002450291](https://github.com/BOLL7708/OpenVR2Key/assets/140105164/f2526cc9-36ac-413e-b375-2c9703464d63)
p 

### Steps to reproduce the behavior

dont know what this is

### Expected behavior

what i expected was for it to show r9 when i press A

### Operating system version

windows 11

### SteamVR version

unsure

### Application version

unsure

### VR HMD

oculus quest 2

### VR hardware

oculus quest 2

### Software to control

steam

### Game

gorilla tag

**Comment by BOLL7708** [comment]
Unblocked just means the SteamVR dashboard has been dismissed, and that there are no keys that are simulated at the moment. Have you set any keys to be triggered in the interface?

**Comment by matty19109283** [comment]
it says the same thing for me can someone help ive got it to work a couple of times but im using voice mod

**Comment by BOLL7708** [comment]
Closed due to no reply.
