### ISSUE TITLE
Everything works but active keys say "Unblocked"

### ISSUE THREAD

**Issue by H4mser** [BOLL7708/OpenVR2Key#72]
### Current behavior

I expect it to say R9 when I press the A button on oculus

### Steps to reproduce the behavior

idk

### Expected behavior

R9 to show when I press the A button on right controller

### Operating system version

Windows 10

### SteamVR version

1.26.6

### Application version

V0.61

### VR HMD

Oculus Quest 2

### VR hardware

Oculus Quest 2

### Software to control

SteamVR

### Game

Gorilla tag

### Additional information

VR was dead at the time I made this post.

**Comment by BOLL7708** [comment]
> VR was dead at the time I made this post.

If SteamVR is not running the application cannot receive input from the controllers. 
It saying `Unblocked` means the last thing it detected was the dismissal of the SteamVR dashboard.

**Comment by BOLL7708** [comment]
Closed due to no reply.
