### ISSUE TITLE
Keys not working

### ISSUE THREAD

**Issue by Declan20000000** [BOLL7708/OpenVR2Key#73]
### Current behavior

my key is R8 but when i set it to F9 it doesn't work. So can you help me with this?

### Steps to reproduce the behavior

Try it bro.

### Expected behavior

i expected to press a button on my controller and it would play a sound *I binded and everything.

### Operating system version

Windows 11 

### SteamVR version

1.26

### Application version

0.57

### VR HMD

Oculus Quest 2

### VR hardware

Oculus Quest 2 controllers

### Software to control

Soundpad

### Game

Gorilla tag

### Additional information

Nil

**Comment by BOLL7708** [comment]
1. Is SteamVR running?
2. Is the SteamVR dashboard hidden?
3. Do you see active Oculus bindings in the bindings interface?

**Comment by BOLL7708** [comment]
Closed due to no reply.
