### ISSUE TITLE
OpenVR Status: Disabled

### ISSUE THREAD

**Issue by casmp4** [BOLL7708/OpenVR2Key#75]
### Current behavior

When I start the application in SteamVR, the OpenVR Status is Disabled, and my buttons are not recognied.
I am linking my headset to my pc with Virtual Desktop. 

### Steps to reproduce the behavior

- Launch SteamVR
- Launch OpenVR2Key from Steam as a Non-Steam Game
- See OpenVR Status: Disabled

### Expected behavior

The controllers should be detecting. It's worked before with the same hardware and software. I re-installed the program but I'm not getting any solutions.

### Operating system version

Windows 11 Pro

### SteamVR version

SteamVR beta 1 26.7

### Application version

v0.57

### VR HMD

Meta Quest 2

### VR hardware

Meta Quest 2 Touch Controllers

### Software to control

Soundpad

### Game

Gorilla Tag ( i know alot of people are trying to have a soundboard here sorry about that )

**Comment by BOLL7708** [comment]
Disabled means the application cannot connect to SteamVR at all. It is supposed to say Connected as soon as SteamVR is available to connect to. Are you launching SteamVR as administrator or something?

**Comment by casmp4** [comment]
No, I'm not currently running SteamVR as administrator.

**Comment by BOLL7708** [comment]
Then it's really weird, because as I said, it means the application cannot connect to SteamVR. Are you running Gorilla Tag on Steam or as a native Quest title? I don't have a Quest myself so I cannot test these things.

**Comment by casmp4** [comment]
I run Gorilla Tag on steam.

**Comment by BOLL7708** [comment]
Then I honestly have no idea what is wrong, you could try the pre-release v0.61 of this app to see if it makes any difference at all, or perhaps put it somewhere else on disk. 🤔 As it is I don't have a Quest nor a Windows 11 gaming machine so as before I'm unable to replicate or debug this. I should really build some kind of logging system into this so people can share that eh.

**Comment by casmp4** [comment]
Okay, when you said launching the game through Steam, I didn't think to launch it while the program was open. Upon doing that I was able to use it. My apologies.

**Comment by BOLL7708** [comment]
Ah, I didn't think that would make any difference. This might be a good clue to what is going on for more people, thanks for sharing!
