### ISSUE TITLE
Vr2key active keys says "unblocked" 

### ISSUE THREAD

**Issue by Cycle89** [BOLL7708/OpenVR2Key#76]
### Current behavior

The main problem is with steamvr i think because whenever I use it on my headset it only opens it on my pc I'm not sure why but steamvr on my pc does appear to track when my headset is on or off/in sleep mode but not able to track my controllers or vibrate them. steamvr also never opens in my headset with doing some out of place seeming things. But otherwise I'm just not too sure why active keys says unblocked and why I can't get it to say none or display which key I'm pressing on my controller

### Steps to reproduce the behavior

1. Run Vr2key
2. Run steamvr via pc or airlinked headset (it will always open on pc idk why)
3. After step two status in Vr2key will go from diconnected to connected headset, default current app id and active keys unblocked
4. Struggle to find a way to fix this whether it be find a youtube tutorial or look all over github or smth

### Expected behavior

steamvr to show up on oculus headset and Vr2key to receive the signal of me pressing oculus buttons this is all needed in order for me to use a soundboard in gtag which was my original goal 

### Operating system version

Windows 11 home

### SteamVR version

1.26.1

### Application version

v0.57/unkown

### VR HMD

Oculus quest 2

### VR hardware

Quest 2 Controllers

### Software to control

Soundpad/steamvr

### Game

Gorilla tag

### Additional information

![Screenshot 2023-08-09 135632](https://github.com/BOLL7708/OpenVR2Key/assets/141875306/c5dbf750-0ed0-4de5-8e71-44d965cba2ff)

![Screenshot 2023-08-09 141824](https://github.com/BOLL7708/OpenVR2Key/assets/141875306/0791c5a0-4727-495a-8d4f-1ce18d79b4c9)

**Comment by BOLL7708** [comment]
Are you running the game off of Steam or Oculus? As you probably have seen a lot of people have problems with this exact combination of software, so the tutorials are clearly missing some step, even though I can't figure out what as I have watched some. One other user said the boot order was important, but it looks like you are following it... https://github.com/BOLL7708/OpenVR2Key/issues/75#issuecomment-1668769515

**Comment by Cycle89** [comment]
It is being run on steam but I use oculus and airlink it to my pc bc I don't have another virtual headset

**Comment by Cycle89** [comment]
ok so I got steamvr to work but now active keys says blocked not sure what that means

**Comment by BOLL7708** [comment]
It should mean that you have the SteamVR dashboard visible in the headset.

**Comment by BOLL7708** [comment]
Closed due to no reply.
