### ISSUE TITLE
i binded the h key and it broke

### ISSUE THREAD

**Issue by mintyclover2022** [BOLL7708/OpenVR2Key#78]
### Current behavior

so i binded the h key to the a button on my controller and it doesn't work, I think that's unfortunate and now I've found out the h key wont work on my keyboard either i  had to type the h key in this by using copy paste. and also i didn't have the steam dashboard. pls help i miss my h key.

### Steps to reproduce the behavior

try it...

### Expected behavior

it should press the key when I press the button.

### Operating system version

windows 10

### SteamVR version

1.26.7

### Application version

idk

### VR HMD

quest two

### VR hardware

oclulus touch 2

### Software to control

steam vr

### Game

steam vr

**Comment by BOLL7708** [comment]
If you can't type an H on your keyboard, if it's not a hardware problem maybe some application has registered it as a global hotkey and as such it consumes the event of typing H. This application does not use global hotkeys but simulates typing keys, as if you pressed them on the hardware keyboard, as such if that doesn't work this application won't work.

**Comment by BOLL7708** [comment]
Closed due to no reply.
