### ISSUE TITLE
Support for Vive Controller

### ISSUE THREAD

**Issue by houdang** [BOLL7708/OpenVR2Key#8]
I guess this is not implemented or tested right?

When I choose the openvr binding I do not see any KeyX names to choose..

**Comment by BOLL7708** [comment]
Correct, as I've retired my Vive I have not set up bindings for it, the thinking was that users can add their own bindings for hardware that is currently unsupported, which in theory should be possible through the binding interface. Sounds like you have bumped into some problems though, so maybe not 🤔

It would be better if everything was included though, of course, my schedule is booked right now but I'll add this to my to-do list, and try get an old Vive controller up and running to test this off 😅

**Comment by BOLL7708** [comment]
Just did a [pre-release](https://github.com/BOLL7708/OpenVR2Key/releases/tag/v0.50) with test support for various controllers, please test this with the Vive Controllers and report back.

**Comment by BOLL7708** [comment]
I did my own testing and I think I got it working properly. You can find included support in the most recent [release](https://github.com/BOLL7708/OpenVR2Key/releases/tag/v0.51).
