### ISSUE TITLE
When tried to start app says ''already opened'' and its not opened

### ISSUE THREAD

**Issue by D13G0PRO** [BOLL7708/OpenVR2Key#80]
### Current behavior

![Captura de pantalla 2023-09-04 184103](https://github.com/BOLL7708/OpenVR2Key/assets/144067756/21a2bba6-ce66-4ef8-82cb-09ec6c3d3cb2)

### Steps to reproduce the behavior

1. tryng to start app
2. Error comes

### Expected behavior

I think that restarting my pc will work but didn't happened nothing just the same error over and over.

### Operating system version

Windows 11

### SteamVR version

1.27.5

### Application version

V0.57

### VR HMD

Oculus Quest 2

### VR hardware

Oculus Controller Index

### Software to control

SoundPad

### Game

Gorilla Tag

### Additional information

Dosen't let open and version is the newest That I could Found.

![Captura de pantalla 2023-09-04 184103](https://github.com/BOLL7708/OpenVR2Key/assets/144067756/bd1bd590-d94d-4ebd-85bd-e113a954d67e)

**Comment by BOLL7708** [comment]
The application registers a mutex to check if the same application is already running. Have you checked your running processes to make sure it's not running while minified and possibly hidden? If you have run the application once before with SteamVR it will automatically register to be auto-launched.

**Comment by D13G0PRO** [comment]
i am dont running anything and i tried to use steam vr dosent open too.

![image](https://github.com/BOLL7708/OpenVR2Key/assets/144067756/141fbc4e-5a62-4075-bd61-5cc3b5d41a13)

**Comment by BOLL7708** [comment]
Just checking the taskbar doesn't mean much. Check the system tray and running processes.

**Comment by D13G0PRO** [comment]
Nvm I fixed it thank you for the help It was an older version and i could find the way to open it thx for the help.
