### ISSUE TITLE
how do i get rid of unbloced

### ISSUE THREAD

**Issue by ftftftyf** [BOLL7708/OpenVR2Key#81]
### Current behavior

wefewfeww

### Steps to reproduce the behavior

WW

### Expected behavior

wfwefewfwefwewewf

### Operating system version

wef

### SteamVR version

wfew

### Application version

wfe

### VR HMD

ewfw

### VR hardware

tj

### Software to control

ooii

### Game

wewe

### Additional information

wfewfwewfwefewfefwe

**Comment by BOLL7708** [comment]
Just hide the SteamVR dashboard.
