### ISSUE TITLE
minimize glitch

### ISSUE THREAD

**Issue by poloooooooa** [BOLL7708/OpenVR2Key#85]
### Current behavior

I can't see the app when I run it

### Steps to reproduce the behavior

1. run app
2. click minimize on launch
3. never see it again 😭

### Expected behavior

to appear in my task bar as minimized

### Operating system version

windows 11

### SteamVR version

don't know

### Application version

don't know

### VR HMD

oculus quest 2

### VR hardware

oculus quest 2

### Software to control

soundpad

**Comment by BOLL7708** [comment]
Is there not even a tray icon? It should minimize to the system tray as an icon, maybe it's hidden in the expandable menu, if there is one. I don't run Windows 11 on my main machine so I haven't tried this on Windows 11 just yet.

**Comment by BOLL7708** [comment]
That is the tray and the tray icons indeed, good job!
