### ISSUE TITLE
How to work on STEAMVR DESKTOP

### ISSUE THREAD

**Issue by LollipopJump** [BOLL7708/OpenVR2Key#87]
### Current behavior

THANK YOU VERY MUCH FOR SHARING, I HAVE NO PROBLEM USING YOUR SOFTWARE WHEN PLAYING OTHER GAMES, BUT WHEN I OPEN THE STEAMVR DESKTOP, YOUR SOFTWARE WILL SHOW BLOCKING, I HOPE TO USE THE JOYSTICK AS A KEYBOARD WHEN USING THE STEAMVR DESKTOP, WHAT DO I NEED TO DO?

### Steps to reproduce the behavior

1，open steamvr desktop
2，push the left stick up button
3，active keys shows blocked

### Expected behavior

When I run the STEAMvr desktop, I push the left stick up button and the notebook on the desktop prints out the W

### Operating system version

window10

### SteamVR version

2.1.4

### Application version

v0.61

### VR HMD

pico3

### VR hardware

pico3

### Software to control

STEAMVR DESKTOP

### Game

STEAMVR DESKTOP

**Comment by BOLL7708** [comment]
The SteamVR dashboard consumes all input events when open, so this applications cannot work while it's visible.
