### ISSUE TITLE
Says that the active keys are unblocked but they dont work?

### ISSUE THREAD

**Issue by Hi12345675yftfydy** [BOLL7708/OpenVR2Key#88]
### Current behavior

what i said

### Steps to reproduce the behavior

idk

### Expected behavior

it too workkk

### Operating system version

11

### SteamVR version

2.1

### Application version

11

### VR HMD

oco 2

### VR hardware

oco 2

### Software to control

gtag

### Game

idk

### Additional information

help

**Comment by BOLL7708** [comment]
1. I don't know what you are trying to do.
2. I don't know what you have configured in the application.
3. I don't know what you have tried.
Help me help you, this is now how you communicate with people to get help.

**Comment by Hi12345675yftfydy** [comment]
ok ill ask someone else thanks
