### ISSUE TITLE
fatal error if in Startup in SteamVR

### ISSUE THREAD

**Issue by Artur0186** [BOLL7708/OpenVR2Key#90]
### Current behavior

I try to launch a game with UEVR injector and when OpenVR2Key is registered in Startup in SteamVR then I get Fatal Error, but when it is not, and I launch OpenVR2Key manually I get no problems.

### Steps to reproduce the behavior

1. Run UEVR Injector
2. Run game
3. press Inject

### Expected behavior

-

### Operating system version

Windows 11

### SteamVR version

2.2.3

### Application version

both latest and beta

### VR HMD

quest 2

### VR hardware

quest touch

### Software to control

High on Life

### Game

High on Life

**Comment by BOLL7708** [comment]
Do you know if you happen to have two versions on your disk? So that your manual launching is a different instance that what SteamVR tries to launch? Otherwise I'm a bit perplexed of why this could happen, I would need you to go into the Event Viewer and look for the crash there.

**Comment by Artur0186** [comment]
I used the same version. Earlier I got the same error every time and I was absolutely sure the the problem was in Startup of OpenVR2Key, but now I tried several times and couldn't reproduce. I will post more info when I will meet the bug again.

**Comment by BOLL7708** [comment]
Will close this in the mean time, can be reopened if you bump into it again.
