### ISSUE TITLE
active keys unblocked?? wont work. present keybinds 

### ISSUE THREAD

**Issue by steamvrgtagplayer** [BOLL7708/OpenVR2Key#91]
### Current behavior

i have reinstalled openvr2key many times and deleted the old file  reset headset and  steam   but nothing seems to work to activate the  present  keybinds 

### Steps to reproduce the behavior

run

### Expected behavior

s

### Operating system version

window 11

### SteamVR version

idk

### Application version

idk

### VR HMD

quest 2

### VR hardware

idkj

### Software to control

idk

### Game

gorilla tag

**Comment by steamvrgtagplayer** [comment]
im not sure but i just now got on and it was working stoped like 30 min in the game now says unblocked again

**Comment by steamvrgtagplayer** [comment]
i was able to connnect the bindings to my soundboard voicemod and it wroked perfect untill it stoped now it wont stop saying unblocked

**Comment by steamvrgtagplayer** [comment]
![image](https://github.com/BOLL7708/OpenVR2Key/assets/155990082/1affd975-5616-4c07-b056-9da03606f42f)

**Comment by steamvrgtagplayer** [comment]
![image](https://github.com/BOLL7708/OpenVR2Key/assets/155990082/36bc7e88-d220-419a-b3f0-9f2fc07a0cc4)

**Comment by steamvrgtagplayer** [comment]
![Uploading image.png…]()

**Comment by steamvrgtagplayer** [comment]
![Uploading image.png…]()

**Comment by steamvrgtagplayer** [comment]
now its working again please tell me how to prevent this from happening pls??

**Comment by BOLL7708** [comment]
I don't know as I don't know what caused the issue. I'm guessing something was moved or the wrong instance was used, or something like that. Now it'll likely be impossible to tell, closing this for now.
