### ISSUE TITLE
Active keys say “unblocked”

### ISSUE THREAD

**Issue by TheMrBean** [BOLL7708/OpenVR2Key#93]
### Current behavior

I am sitting in the steamvr home, the dashboard is not open, and openvr2key still says “Active keys: Unblocked”

### Steps to reproduce the behavior

Open openvr2key.
See that the active key text says “unblocked”

### Expected behavior

Open openvr2key.
See that the active key text says “none”

### Operating system version

Windows 11

### SteamVR version

Most recent

### Application version

1.57

### VR HMD

Quest 2

### VR hardware

Quest 2 original

### Software to control

Voicemod

### Game

Gorilla tag

### Additional information

N/A

**Comment by BOLL7708** [comment]
`Unblocked` means no button has been detected yet so the status message has not been overwritten. `None` shows up after mapped button input has been detected and then released again.
