### ISSUE TITLE
OpenVR2Key Crashes whenever I open a game.

### ISSUE THREAD

**Issue by MonkeEatingRock** [BOLL7708/OpenVR2Key#98]
### Current behavior

Whenever I am in Steam VR (Not in a game) The OpenVR2Key works perfectly fine, HOWEVER when I try to open a game, OpenVR2Key just crashes for no apparent reason.

### Steps to reproduce the behavior

1. Run Software. 2. Run Game. 3. Software Crashes.

### Expected behavior

I expected this software, so I can go to Among Us VR and troll people using Soundpad which is a soundboard.

### Operating system version

Windows 11 Home

### SteamVR version

2.2.3

### Application version

0.57

### VR HMD

Oculus Quest 2

### VR hardware

Oculus Quest 2 Touch Controllers

### Software to control

Soundpad

### Game

Among Us VR

**Comment by BOLL7708** [comment]
Did you put this in Program Files or similarly? The application does not support asking for administrative rights to create folders so putting it in a restricted area would cause it to crash.

**Comment by MonkeEatingRock** [comment]
I already figured it out. Whenever I tried running it from the menu where u click the windows key on your keyboard it just didn't save anything and when i tried to join a game it crashed but when I opened it directly from the folder it worked for some reason it had everything saved and it was working.

**Comment by BOLL7708** [comment]
That is curious, maybe a Windows 11 thing, I'm still on Windows 10. Thanks for elaborating in any case.
